# Toxic Comments Classification - SVM

#### Author: SAFAA ENNACIRI - ENNS11538307                                 
#### Research Director: M. HAKIM LOUNIS

Dataset: Toxic Comment Classification dataset is a dataset of comments from Wikipedia’s talk page edits.  It is avaialble at Kaggle (https://www.kaggle.com/c/jigsaw-toxic-comment-classification-challenge/data). 


The comments are divided in two classes: toxic and normal.

# 1. Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import pickle, re
import time

from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.metrics import f1_score, recall_score, precision_score, accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.svm import LinearSVC

# 2. Data Preparation

In [41]:
# Load training data
df = pd.read_csv('../../Data/train_set3.csv')
df.head()

              Tweet ID                                               Text  tox
0  1230482808457527297  BREAKING: Many leading Chinese scientists are ...  0.0
1  1244980592615116800  If China can kill us, they can kill you too @A...  1.0
2  1244899032771604480  Fuck u Chi Na!!! Karma is coming soon !!! The ...  1.0
3  1244895530720710656  Some Chinese are horrible as fuck! #ChinaLiedP...  1.0
4  1244341105879142407  @ScottGottliebMD you are a "doctor" and you be...  1.0

In [42]:
df.describe()

           Tweet ID          tox
count  2.104000e+03  2104.000000
mean   1.240002e+18     0.486217
std    6.711621e+15     0.499929
min    1.215597e+18     0.000000
25%    1.232951e+18     0.000000
50%    1.244263e+18     0.000000
75%    1.245405e+18     1.000000
max    1.251185e+18     1.000000

In [44]:
for x in range(2000):
    print(df['Text'][x])
    print ('*******')

BREAKING: Many leading Chinese scientists are starting to speak out and say COVID-19 (coronavirus) originated at a government bioweapons research facility in Wuhan, rather than the widely-held belief that it emerged from the city's Huanan seafood markets.  https://t.co/DsxwJSAox2 https://t.co/TbshN8eDni
*******
If China can kill us, they can kill you too @AngusCh89615720 @Heefg14 @Jothehkgirl @jonathanseual86 @SammY91318198 @marielSiviglia @op12381932972 @Makhk6 @AWMF5 @HMW79256809 @Senthil557 @wasteslave @valwonghk @SallyGunner0331 @bhikshu2007 @Mark48994372
*******
Fuck u Chi Na!!! Karma is coming soon !!! The CCP Virus 🦠 （virus origin wuhan）😡😡😡Poor child 😭😭😭🙏🙏🙏 Now, Wuhan pneumonia is still a very serious outbreak in China. But these scums are still to beat up dogs the street.
*******
Some Chinese are horrible as fuck! #ChinaLiedPeopleDie #BoycottChina #WuhanVirus
*******
@ScottGottliebMD you are a "doctor" and you believe that shit?  you chinese hack...  #ChineseVirus
*******
The recent #coronavirus has so far killed more than 1,300 people around the world. But meanwhile, the #flu has killed at least 12,000 people in the U.S. alone: https://t.co/rwV56m6B0w
*******
@realDonaldTrump Make sure u Fuck China and their propaganda #ChinaLiedPeopleDie #ChineseVirus
*******
@ChineseEmbinUK Fuck your China , this whole shit that the whole world is facing right now and the deaths of people the guilty of all of this you China by lying about this Chinese virus or Wuhan virus. #ChinaVirus
*******
@AliciaRedd2 @itsJeffTiedrich @realDonaldTrump I FUCK YOU baby, beautiful Only trump have guts to say CHINESE Virus and to take action against china. https://t.co/VTiOBn27zU
*******
@HuXijin_GT just another example of what piece of shit liars you people are. https://t.co/zbFSuHyEgR. #ChinaLiedPeopleDied #fukchina #BoycottChina
*******
some girl said this to me after calling me a chink
*******
@cutelmgs @PeopIeAwesome #coronavirus Report has been published first time and results are extremely serious.   Coronavirus has become the biggest challenge of 2020 in front of Scientists and health experts.  Like, RT: https://t.co/lKia09KKE9 #CoronavirusOutbreak #wuhan #chinavirus #coronaviruschina
*******
@MikeNov47450872 tl;dr my Qanon niggas think a happening is gonna happen today. although it does sound reasonable that another major happening could happen due to chink virus.
*******
Trailer for the new #BladeRunner movie! 😬 #COVID #coronavirus #COVIDー19 #china #WuhanCoronavirus
*******
I'm CONFUSED. IF THE VIRUS IS TRANSMITTED HUMAN TO HUMAN BUT THERE ARE NO HUMANS ON THE STREETS BECAUSE OF THE 60M PPL QUARANTINE, THEN WHY ARE THEY SPRAYING THE STREETS?  Another video of chemical disinfection in the streets of Wuhan #coronavirus  https://t.co/aRlkNuNIhS 01 #FBR
*******
Was the #coronavirus planted in China by US operatives? https://t.co/KqqurjtQDC
*******
@43978667_Ip @shyamjai @OpIndia_com Now the Chinks are also down, with the Coronavirus. What are going to do ?   I have noticed a lefties, are doing havan and eating gobar, to prove their loyalty to India. 🤣🤣🤣  The AAPia Rathi has open a new app to loot people of their money. https://t.co/PA8GAk29qv
*******
@_naimani No, calling it the Chinese Corona Virus is not racist. Historically speaking, diseases of this magnitude are named after the country or region they originate from. Also, whats wrong about holding the country accountable for their lack of food and animal regulation since its been
*******
Dear @PattyMurray: As your constituent, I would like you, as the ranking member of the Senate Committee on Health,… https://t.co/xYhbRTxqkl
*******
#IamNotAVirus Will China ever stop spreading viruses as they have done historically?
*******
#ColonaVirus #CoronaVirus #ChineseTourists  😂😂😂 colon-a vrius 😂😂😂 笑死我啦!!!   #MustWatch #爆笑   Chinese Tourist Caught Shitting On Owners Property - New Zealand - https://t.co/Yu3vr6KuJQ
*******
@saataarkar @globaltimesnews fuck #chinazi fuck #CommunistVirus
*******
Got on the Victoria Line today to seven sisters and some chinese cunt coughed on me. Decked the cunt in his throat but now im worried that i’m gonna get the bat virus ffs
*******
This is indeed a fact. There are videos of Nancy encouraging the celebration of Chinese New Year and downplaying the virus. Leaders in New York the same. So get off Trumps ass you tools.
*******
@WatchdogsU @AnnLinde Swedish sanctions would not be affective. Since we are a small country. Would be like piss in rhe ocean. I would tell the chinese ambassador that he is not welcome in Sweden and fuck of to China. And hope he gets the coronavirus.
*******
@vwang3 As was once said : #China is No. 1 - if you do anything that causes the perception of China to change from… https://t.co/SogBppKO5X
*******
#WuhanVirus/#CoronaVirusUpdate:  #FakeNews, The #EnemyOfThePeople, is the US epicenter of the #WuhanVirus/#Coronavirus freakout. If there's anyone that should be in a panic, it's the people near #Kirkland, WA or friends/family of recent Chinese travelers.  Enough Fake News! #KAG
*******
As China ramps up efforts to control the narrative around the Chinese coronavirus outbreak, it is also expanding its efforts to leverage online platforms to track down people who dare to speak out. #fuckChina https://t.co/v2yMOAm1ZI
*******
@marcorubio True, people are struggling but that doesn’t make it right to call this the Chinese  virus.  It’s racist and you know it.
*******
@NBCNews Chinese Virus. They made it, released it, and hid it. It is time they own it.
*******
Karma is a real bitch 👏🏻💃🏻🍾🥂🍻🎉🎆 #若然未報時辰未到 #HongKongProtests  #HKPoliceTerrorists  #5DemandsNot1Less #WuhanCoronavius
*******
@kellysszn @70s90s Keep believing in yourcown lies, you UGLY CHINESE COMMUBIST.  The US will gather EU, SK, and Japan to DESTROY China after we deal with the Chinesevirus.   Kill all Chinese
*******
@RepAdamSchiff Ignorance must be bliss. The Chinese virus has killed people all over the world because the Chinese… https://t.co/xmSVn0fUXt
*******
@bayareahausfrau @TiredOfBob not a SINGLE death...just 10’s of thousands of cremations.  #ChinaLiedPeopleDied https://t.co/pPZtUnObwD
*******
@Jay_Qi37__China @EnzoMazak @eille68577793 @andrewbogut Your country ruins the world.  Heard of corona virus. Hope it's wipes out u shit cunts
*******
Look at These Chinese Bastards America🖕🖕 LET'S KEEP THESE CHINK BASTARDS OUT OF AMERICA!! #ChinkVirus #ChineseVirus #ChineseVirusCorona #ChinaLiedPeopleDied
*******
@ALLENYEAH123456 @PDChina Lol retard it comes from your infested country like always because an anus of a bat is considered delicious there. Also no there's no proof lol. Just Chinese lies like always. No it struggles with ethics about privacy. Unlike your doctor. Go eat some cats you dirty virus pig https://t.co/RAHQQYlqNi
*******
Chinese Virus , this nigga sick 🤣🤣🤣🤣 https://t.co/474NJqFr6G
*******
@HuXijin_GT just another example of what piece of shit liars you people are. https://t.co/zbFSuHyEgR. #ChinaLiedPeopleDied #fukchina #BoycottChina
*******
Give small business owners a break , anything coming from China is delayed due to coronavirus.. unless you want that shit, relax.
*******
Big Ten, Big 12, SEC and AAC Cancel Tournaments Because of Coronavirus Outbreak https://t.co/3GK8RJo4G7
*******
The MSM gives you disinfectants that MAY kill the virus.  The disinfectant that KILLS the virus is Virkon S. It's being used by many Asian countries governments including China.  Ask yourself why Virkon S wasn't on this list? #coronavirus https://t.co/SengnW4vpW
*******
@LauferLarry @Yamiche Calling it a Chinese virus DOES affect peoples health! https://t.co/pijAKzpQfQ
*******
@mindmixradio @realDonaldTrump Niterz...outta here and the Chink virus can eff off!
*******
Another methodology change = another wild swing in new cases of #COVID19. We dove into implications w ⁦@ScottGottliebMD⁩ + concerns about undetected cases &amp; whether local US health depts have enough funding. ⁦@DrLeanaWen⁩ put it bluntly: “No.”  https://t.co/NSg78V8bAq
*******
6 ways the US government could help contain the new coronavirus https://t.co/iRJ8wnWzXW
*******
@Cartoon_MOMS Why is the penis pixilated? Asians are Fucking bizarre. Oh and thanks for the Coronavirus. Bat eaters!
*******
They probably would have fucked the snake before killing it. #ChineseVirus Chinese are Virus. https://t.co/xCcsk6pOuS
*******
This is not a “Chinese virus”. Asian people are getting violently attacked, screamed at... I am seeing my friends f… https://t.co/meqOmgj99r
*******
@PDChina @China_Amb_India Fucking asshole , put the whole world in panic mode . China should pay reparations to all countries #ChinaVirus
*******
China MUST STOP blaming and persecuting Africans over COVID-19. https://t.co/Ui0XLOjY42
*******
『SARS-CoV-2 Coronavirus Multiplex RT-qPCR Kit (CD019RT) - Creative Diagnostics』 https://t.co/kbyR87rlYQ
*******
I love when they slap me on the ass. And then they kiss her #St. Petersburg  #nudemodel #coronavirus https://t.co/4zkngAr8Wx
*******
@McFaul #coronavirus Report has been published first time and results are extremely serious  Coronavirus has become the biggest challenge of 2020 in front of Scientists and health experts  Like, RT: https://t.co/lKia09KKE9 #CoronavirusOutbreak #ChinaVirusSesungguhnya #WuhanVirus #Wuhan
*******
@HillaryClinton @NotThatKellyAnn Yes we even surpassed the Country where the so called “Chinese Virus” began. Isn’t it ironic.
*******
@COVID_19NEWS I'm so fucked I warned ppl about coronavirus but ppl didn't listen because president Moon said coronavirus will soon end. Don't come to east asia guys. It's like three countries are betting who's falling first
*******
Quick reminder that being offensive towards Yoko Ono for her race is never acceptable. You are within your rights to dislike her attitude and actions but there is no excuse for racism or hatred.  Also, stop being offensive towards Asians in relation to CoVID-19 - unacceptable. https://t.co/ihAGImy21B
*******
@JoeWongComedy You mentioned in your live show today that you were so mad once at the backstage of a theater because the comedians called you “chink”. It reminded me that when I was pursuing my master degree one white girl told me to “open your eyes”.i was so upset because I had big eyes...
*******
Wtf Chinese shit in my coke https://t.co/M42QBrFLia
*******
@SuperLoliStark He was like fucking take it. Really wtf. And the paper was an ad...saying fear of coronavirus? Call us we will exterminate it from your house. All written in Chinese. Just really wtf. If you don’t want it don’t give it to me. Trash can is beside you. Throw it there.
*******
@catherinecookx you can’t mess with this shit 😂
*******
@Cheezman20 @IlhanMN BETRAYED AMERICA.  THE CHINESE UNLEASHED A FUCKING VIRUS ON THE AMERICAN PEOPLE.
*******
#fuckchina for eating dogs. For boiling them alive! I hope there comes a day, where those who are doing this, are legal to kill the same way you kill animals. I hope you end up being tested on and boiled alive! This is the reality you people want to live in? Filthy country!
*******
#ChinaLiedPeopleDied not only that but people losing their jobs everyday and the economy going to hell. And whoever says blaming China is racist you can go suck a dick.
*******
Fuck China,spreading the virus all over the world,shame on you! #WuhanHealthOrganisation #ChinaLiedPeopleDied #ChinaIsAsshoe #ChinaVirus
*******
@argyleumbrella @business Yep. Fucking MONTHS ago! 👍 #ChinaLiedPeopleDied
*******
There’s little doubt the Coronavirus is a boon to disaster capitalism https://t.co/wbrVwSp7sg
*******
@wikizhiyu @philhenderson @Lord_Sugar Dont worry its going to happen. The world will boycott chinese made shit. The world is sick because of your filthy habits #ChinaLiedPeopleDied
*******
No one: China people 😂 https://t.co/kBxHOWBkDv
*******
@yjpc06 @holymation Fucking chinese virus
*******
Found a great deal on coronavirus at Wal-Mart. They were practically giving that shit away. https://t.co/JrD2SBrV3Q
*******
@NaiobiT Ye cus the coronavirus hates all black ppl so it just goin past them like "Hi bitch... Bye bitch" Whoever said that...
*******
No more fake news. ▪️ #ChinaLies #CCP #Chinazi #BoycottChina #WuhanCoronavirusOutbreak #AnywherebutChina.▪️ https://t.co/piLneVcegG
*******
#coronavirus Were all going to die because some dirty chinks didn't want to curb their eating of bat soup and dogs lmao
*******
@mattwander12 I barback on the weekends and I hear that stupid shit all the time to the point where I wish we actually had the coronavirus in a bottle 😂
*******
@WBYeats1865 Fuck the chinese make a lot of people died in this #ChineseVirus. They will go to hell #ChinaLiedPeopleDie
*******
@zlj517 Mother  fucker china virus..what about sars..it not the first time. Fuck CCP ( China  Communist Pig) and Xi " winnie the POOP" XinPIG. 🖕 CGTN fuck u too..you guys continu to lick balls of your leader. China virus and Xi xinPIG need to bow and apologize to the world #chinaVirus
*******
I AGREE WITH @SenTomCotton  THE CORONAVIRUS MORE THAN LIKELY IS MAN MADE @CNN WOULD PROTECT THEIR FRIENDS CHINA &amp; THEY HATE PRESIDENT TRUMP &amp; AMERICA. CHINA HAS BEEN STEALING OUR TECHNOLOGY  &amp; WOULD DO ANYTHING IN THEIR POWERS TO DESTROY AMERICA 🇺🇸
*******
Who wants to fuck me in the mouth? I'm a bad girl 😈 #animalsex https://t.co/vjVs2vPWkA https://t.co/vjVs2vPWkA #Grand Prairie #coronavirus https://t.co/7pGeva1HHs
*******
fucking communisten!  https://t.co/velVFoU04w
*******
#coronavirus #CoronavirusOutbreak u fucking chinese.. can u stop eating bats... dogs.. snakes... cockroaches... fucking insane... what u have led the world into
*******
With #China accusing the #US military of infecting Wuhan with 𝘸𝘦𝘢𝘱𝘰𝘯𝘪𝘴𝘦𝘥 #COVID19, after they sent out millions of defective masks &amp; faulty test kits?  FUCK CHINA, I'm calling this the #WuhanFlu from now on. #中國可以去地獄 #送中國下地獄 https://t.co/02NaXOm4ow
*******
China leaked that shit from a lab 100%
*******
They probably would have fucked the snake before killing it. #ChineseVirus Chinese are Virus. https://t.co/xCcsk6pOuS
*******
Bruh, AIDs is a sweetheart, it let's you raise your kids see them graduate, hustle through young adulthood, get jobs, settle, get married, and in some cases you see your grand kids. Corona virus is🤔 it's, write your will right now that's some next level bitch. Hand me a 2nd mask
*******
How abysmally reckless can #IMPOTUSthe3RD be?! Calling #COVID19 A FUCKING HOAX??  This is how people fucking die you son of a bitch! My fucking ghad I sincerely hope your #MAGATS don't REALLY believe your fucking lies. Your LIES cost LIVES @realDonaldTrump this ISNT China, ass.
*******
@Gailyfleur @nytimes Communism created wet markets in Wuhan where the virus originated... Communism starved millions from the 40s-70s in the SU and China. Congrats on baseball and cigars! Other than that eat your state run media shit you fucking low life communist cunt
*******
Fuck off you mother fucking, reptile eating chinks! You have lost the world's respect you murdering cunts!
*******
People who put #Coronavirus hashtags in their ass pics to get more likes and followers are deplorable
*******
@annjayloo "why i got covid-19" charot HAHAHAHHA
*******
@belkiswille @PrimeministerGR It’s ccp virus which killed those innocent all around world...it’s ccp’s dirty and inhumanity plan which is still killing more innocent people all around world...evil ccp must be punished for a better life of all chinese as well as the rest of world people... https://t.co/91WxQ8Wf0a
*******
Someone called @EvanderYang from a country which has sent #chinesevirus to the world ,is tweeting a video of a Muslim maulana raping a child and tagging that Indians r like that Lol don't worry they will rape your kids too😂🤣🤣🤣🤣🤣
*******
Once again #Hindus terrorist attack in India burning mosques killing Muslims, my God, send soldier of your soldiers to Hindu like sent #coronavirus to China &amp; Since emergence virus China didn't kill Muslims my God, send to Hindu greater than virus &amp; do not find treatment for it https://t.co/WZ0IPszFbU
*******
@el_mago_jinete @tyrone_brother Stop eating vermin and exotic animals, you damned slant eyed COVID-19 spreader! Mind YOUR damned business, Ladyboy Ling Ling! 🐀🥡🥢
*******
So fucking stupid. This virus is ALL on China and their communist regime. Linking it, the market sell off, and the upcoming recession BECAUSE of the virus to Trump is just pathetic.
*******
#YoMuzziesSoBad , they h@te Hindus so much, they started gathering deliberately to get infected with #ChinaVirus &amp; do #CoronaJihad . Most islamic countries shut their M0SQUES &amp; sent #TablighiJamaat to infect Indian Muslims &amp; hurt Indians. See what Muslims believe: https://t.co/BGbSSUCyxL
*******
Very sad , please take this shit Seriously #ChinaVirus  https://t.co/E6nzd4LpT6
*******
#ChinaLiedPeopleDied It's all because of this fucking country...
*******
@narendramodi CCP killed Xinjiang and Tibetans,I remain silent;  CCP kills Hong Kong people with virus, I remain silent;  CCP killed all Chinese with virus ,I remained silent;  Today, CCP kills people all over the world with virus, please don't be silent! Because ccp turns the earth into hell https://t.co/yEYKP9dUjN
*******
@DailyMirror China is not another planet you know.
*******
The Gray Plague: What The Fuck Is Going On In #Qom? #CoronaVirus #WuFlu https://t.co/fLczl6XCqc
*******
With #China accusing the #US military of infecting Wuhan with 𝘸𝘦𝘢𝘱𝘰𝘯𝘪𝘴𝘦𝘥 #COVID19, after they sent out millions of defective masks &amp; faulty test kits?  FUCK CHINA, I'm calling this the #WuhanFlu from now on. #中國可以去地獄 #送中國下地獄 https://t.co/02NaXOm4ow
*******
@AdamYoungHK @StandNewsHK Fuck all fake rubbish 76 ass hole hk fucking popo wish all they can get corona wuhan virus asap and die immediately
*******
@NYGovCuomo Go ahead and thank them for the whole fucking pandemic you incompetent asshole.  @WuFlu. @fuckchina
*******
#BREAKING: Military in #Iran preparing to quratine Qom after two people suddenly died of #coronavirus today. Highways are being shut down. (DEVELOPING STORY) https://t.co/eCib0GwBQc
*******
@LeoVaradkar Why is he licking China’s boots. Enough. China started a war. I’m sick of watching these ‘leaders’ kiss the ass of a country who has single handedly infected the world w/ a deadly virus and lied. #ChinaLiedPeopleDied
*******
CHINK STINK
*******
@DonaldJTrumpJr If they would’ve put half the effort into the Chinese virus they did on the disgusting impeachment shit who knows what could’ve been accomplished already!
*******
Coronavirus exposes chinks in Chinese and Hong Kong firms’ remote-working, business continuity capabilities https://t.co/I1IcORyIxe
*******
@Cheezman20 @IlhanMN BETRAYED AMERICA.  THE CHINESE UNLEASHED A FUCKING VIRUS ON THE AMERICAN PEOPLE.
*******
@BNODesk Why does anybody still give a shit about what china is saying? They are telling one lie after the other either way. #ChinaLiedPeopleDied
*******
NOT #COVIDー19!!  IT SHOULD BE CALLED THE #WuhanVirus !!!!!  Also, Do Not let "WHO" get rid of their responsibility!!  #WuhanCoronavirus  #Wuhan #coronavirus  #FuckCCP #fuckChina #FuckWHO #BoycottChina  #CCP_is_terrorist  #China_is_terrorist  #HongKongisnotChina #TaiwanisnotChina
*******
No kiss, No hug #coronavirus
*******
White House to Cancel In-Person Meeting of G7, Citing Coronavirus Outbreak https://t.co/DSYy5cpdqV https://t.co/yKVfhLExiD
*******
These chinese are some fucking breeds.
*******
Freedom and democracy lit a shit bag on Hong Kong’s doorstep and just rang communism’s doorbell in China #StandwithHK
*******
@realDonaldTrump @nytimes You’re just mad because you maybe can’t use the racist term “Chinese Virus” anymore, you loser!
*******

I remember when we first hear about the corona virus we was all let damn them Chinese niggas is wild now look 😟😟😟
*******
@MeqdadLocation Fuck @HassanRouhani and @AmbChangHua #ChineseVirus
*******
You fucking evil pieces of shit @china #china #fuckchina #evilonearth
*******
@jling_lee @GaryPNabhan @HuXijin_GT Hi, chink Lee. A beauty, isn’t xi? https://t.co/V60dWgPDB0
*******
Weird shit inside the gold mine....Undercover Investigation Indicates Coronavirus Death Toll in Wuhan Much ... https://t.co/ck7f2HCMGa via @YouTube
*******
@LHGHKG @RyanAFournier @Aloha88617098 true "shit" #BoicoteAChina #chinazi  #StandWithHongKong #ChineseWuhanVirus #ChinaLiedAndPeopleDied #ChinaLiedPeopleDied #ChineseVirusCorona #chinaVirusMadeInChina #ChinaMustPay #ChinaWuhanVirus
*******
Only difference is that we don't have 60+ years of anti imperialism propaganda. Because it's the same thing the west loses its shit over China.
*******
Why everyone is remaining silent right now is a little alarming. Shitz serious y’all!?! 🙏  #prayforchina #notaflu… https://t.co/OS46AYynSm
*******
You are right. But it still completely pisses me off. Plus the market. I lost my ass 3 days in a row. I am so stupid. I am pissed. #FUBS #BERNIEISACOMMIE
*******
Obito(Coronavirus)- wassup bitch  Minato- Oh shi....t  Obito- I'm gonna come get you https://t.co/sFkSlPazZ9
*******
would be great. However, if the virus does indeed discriminate on race, and only targets East Asians, then the WHO head's comments make sense. This raises yet more questions: If the COVID-19 is a race-based bioweapon, who created it? The US? Israel?
*******
@CNN It's Wuhan Virus, now fuck off
*******
Also! I’m sorry about my sudden hiatus the past few weeks! Things have been very stressful here due to Covid-19 Everyone stay safe💕
*******
@WHO @pahowho @WHO_Europe @WHOEMRO @WHOSEARO @WHOWPRO @WHOAFRO @DrTedros Definitely #ChineseVirus is airborne..!  Remember these Puppets in the hands of 11Jinping once said there's no human-to-human transmission..?  @DrTedros @WHO @UN you all suck big..! Time to shut your #Chinese Market. #ChineseVirus19
*******
@NorbertElekes If any country diplomat has died due to this chinese virus, it should be treated as act of war on that country.
*******
@BBCBreaking Even today @ 50 countries infected with China Wuhan coronavirus exports &amp; people dying every day WHO STILL refuses to call for travel bans against major infected countries and call it a pandemic! Entire WHO leadership should be PROSECUED for criminal negligence against humanity.
*******
Tonight is my last night of my long vacation in China. Tomorrow night I have to go to bed knowing I have to teach 50+ students Public Speaking online the following morning. How the fuck do you do that? #noclue #China #coronavirus #onlineteaching #FAIL
*******
@sotiridi This man was definitely killed by them police. China is fucking ruthless
*******
I wasn't fucking around when I said you could do more for the environment and reducing pollution by initiating a nuclear attack on China.
*******
R they really gonna deal with this here like the idiots in china? Shit....
*******
My heart goes out to all my indigenous brothers and sisters of the Navajo Nation #imua  https://t.co/6L1DURUVdq
*******
@gui_canz @OnlyinOntario @Lumberist @CarlosA86462594 @ZackSlater54 @allenlafrance @NewImproved9 @Herb71295950 @He48300141 @Tigergeorgie @6831Bryan @qfd_bruce @patriot_north @FEDDUPP2 @JPLAR1943 @TonyMon47235935 Damn #chinesevirus #WuhanVirus @nostradamous195 @ElevatedMonkey @Danskine1 @RosieBarton @CBCQueensPark @PattyHajdu https://t.co/OwEb4YgiD4
*******
@Acosta 👍👍👍👍👍❤️DJT❤️❤️❤️❤️  America loves Chinese food, and this virus came from China.
*******
Well no shit. #coronavirus https://t.co/1OLHdCVt8p
*******
@LoriinUtah @realDonaldTrump I'm far from an expert on subjects organic or martial, but I recall reading a while ago that China has a biological weapons lab in Wuhan. If true, the Wuhan virus may have escaped into the wild by accident.  Their sin was trying to hide the leak.  https://t.co/5enpJw4c0B
*******
6.64 million jobless claims... Fuck the Chinese Fuck the Wuhan virus Fuck the Democrats Fuck the toilet paper hoarders Fuck the media Fuck this quarantine
*******
Somebody said so the corona virus stopping y’all from eating Chinese food but HIV not stopping y’all from fucking raw 😭😭
*******
@Pappiness @realDonaldTrump Chinese virus sounds right to me.
*******
@OldGeorgeWash @CCTVAsiaPacific Most are business men that went to buy goods from #Guangzhou #china #RacismIsAVirus
*******
Lies, #Hydroxycloroquine cures 99%. How could #WuhanVirus kill millions. They think we are stupid.@realDonaldTrump She even says and ruin economy. We have been duped.
*******
@jtao98 @Olympics @Paralympics Chink man, sickness of Asia is here. https://t.co/q65gNnVViJ
*******
@shannondd76 @DeniseGundelfi1 @RealJohnDennis @EricTrump @kyleraccio That doesn't say that "WHO said the virus was not transmitted human to human"  It says "Chinese authorities have found no clear evidence of human to human transmission..."
*******
@heretosay1 @pangsb @globaltimesnews I will say it loudly #chinesevirus #fuckchina https://t.co/tOp3vi5XvU
*******
Be America buy America, #MakeChinaPay , #ChinaIsAsshoe
*******
Next time someone calls me a chink. Thanks @AndrewYang for solving racism. 😇 https://t.co/8zC8tEg1hD
*******
Considering there is no such thing as the Chinese Virus https://t.co/3GSJotpCoZ
*******
Poll:  1/ 2  Do you believe as I do that the TIMING of the Wuhan Virus that's: Shut down our economy, Costing Americans their Jobs, Harming our Children's Psyche , Weakened our National Security, and Killing thousands of Innocent Americans-is just to damn coincidental - cont
*******
📢Calling all #Radical #Counsellors &amp; #Psychotherapist's 📢 We are meeting on 26th April, 11-1 to reflect, learn and respond to COVID-19 in #Intersectional, #AntiOppressive, #therapeutic &amp; practical ways. Please join &amp; share.    https://t.co/cOlEjCfQ3k
*******
@jazzy_saxophone @K0A0O0R0U0 @Sankei_news Hahaha no don't worry ,we will fuck those Chinese up ,let the Chinese virus pandemic end ,we are ready to destroy China 🇮🇳🇺🇲🇯🇵 😈
*******
If you’re just now learning that China fudges the numbers on EVERYTHING, you don’t need any help from the #Coronavirus being completely fucked.
*******
@chenweihua It’s ccp virus(NOT CHINESE or CHINA)which killed those innocent all around world...it’s ccp’s dirty and inhumanity plan which is still killing more innocent people all around world...evil ccp must be punished for a better life of all chinese as well as the rest of world people...
*******
if you actually think you can get the average #filthy #ignorant person to change in order to curb #coronavirus #covid19 #bioweapon try shitting in one hand and wishing in the other and see which one fills up first
*******
Lol, shut your ass up you fat covid 19 virus having fat chinese elephant. What are you the asain tubby emu?? LOL. Dont talk about other peoples looks when you look like you come out of fish hooks you fat obese milo LMAO. Lol sit down four eyed overweight f@ggot LMAOOO. https://t.co/9H0L27iglC
*******
@MelindaMann01 @PoliceBelief @jennyleong @JaneCaro The virus ORIGINATED in Wuhan, China. By originated I mean "began", and this ties to geography not people. Only a complete racist could interpret the geograpical naming of a noteworthy event as racism.  What next, those government mandated "made in China" stickers are racist too?
*******
For the whole of April, even @YouTube puts video quality restrictions, as if we were already not having enough of those. This Chinese shit is wrecking my nerves now.  #ChinaLiedPeopleDied  #ChinaLiedHDExperienceDied
*******
@VanillaGuise @eugenegu Are you kidding me !!?! You are blaming on the president instead of some ass hats get real... it is the Chinese virus and the Chinese government originated it
*******
"The normal flu kills tens of thousands of people every year, and in the weeks since the coronavirus has emerged, will have killed more people around the world than the coronavirus has in China"  This is dangerous propaganda from a respected source
*******
we all getting coronavirus all cause some niggas in china wanna eat fucking bat soup 😐
*******
Please note that in 2015, an estimated 200 people died of natural causes - such as flu - on cruise ships. Any death is sad, but it seems to me that this whole virus scare has as much to do with social experimentation/control as anything else. Now, where did I put me tinfoil hat?
*******
@1776Stonewall There's a doctor who treats 1000's of Lupus patients with HCQ and has sent a letter to the FDA sayin… https://t.co/RSUSczIJIw
*******
@CNET Fuck chinese editors!  https://t.co/1Z3jf2Tf1d  #ChineseVirus  #COVID19  #coronavirus
*******
Man! I hope I don't get that Commie Chinese Wuhan Lead in Their Toothpaste Coronavirus! Fucking inscrutable virus! 😡😡😡   😄😄😄😄
*******
@David_Leavitt If you think calling it the Chinese virus is racist, just wait till you hear about Ebola!!!
*******
Now i see how the Koreans with Chinese last names came to live in the peninsula.  The Chinks were running away from the problems in mainland China to Korean peninsula since 2 thousand years.
*******
#coronavirus #Wuhan #pandemic #CancelEverything #ChinaCoronaVirus #TomHanks  Please don’t forget it’s China who started this shit https://t.co/Sqahsj0VBe
*******
#ChinaLiedPeopleDie #ChineseVirus19 #WuhanVirus #ChineseCoronavirus....#ChinaGovernment has blood on its hands. #Lockdown economically crippling many but many countries..now how dare they say they helping globally? #China to be #Sanctioned by every country. People dying, ppl sick
*******
At the dr and the first thing they ask is if we’ve been to China in the last 4 days... Like ya bitch just hopped off my private jet this morning ... #coronavirus
*******
@Acosta It's not the Chinese virus The Chinese people didn't create it and the people are innocent IT IS HOWEVER TH… https://t.co/HmR9fn5ibw
*******
@GhostMan868 Better yet...use it on the FUCKING CHINESE WHO INVENTED THIS SHITTING VIRUS
*******
@Haha62181120 @HuXijin_GT FUCK YOU CHINES VIRUS  Name : ChinesVIRUS Birth Place. : WUHAN China Date of Birth : 1st nov 2019 AGE : 5 months Total Crime : 30, 000 Human death Award : CHINES VIRUS noble prize Objective : Destroy Human   FUCK YOU CHINES VIRUS   You eat potty all world sending you CHINESVIRUS
*******
Can you say coverup! People are dropping like flies. What are the real numbers?  #coronavavirus #covid19 #BioWeapon The truth is out there.  Is it the fake flu, coronavirus or the T-Virus. Is humanity in trouble? Is the world economy fucked? Do we all have to worry?
*******
#airports &amp; #aircrafts, they must use disinfection products such as spray or #wipes .Because #passenger hygiene matters.Use #Virus-Guard.It provides the most effective #disinfection #wipes for #inflight use against #COVID19 #WuhanCoronavirus #Coronavirus #MERS #ChinaVirus #Corona
*******
@IanSunio china oilz
*******
This type of shit makes no sense. The lady was just at a church and about 20% of the practitioners got sick, yet people infected flying in to Canada, America and Europe on 14 hour flights with extremely close contact aren’t spreading the virus to everyone on board? Hmmmmm???
*******
n ppl tried to come at me saying “stop calling it da chinese virus” when they created da shit even after governments stopped funding those dangerous ass trials. look stupid n defend da chinese if u want, they wanted dis to happen.
*******
@chukaobi It’s because it’s coming from Trump in a place where racial tensions are high. He was wrong to call it Chinese virus.
*******
@techreview No pictures of non-Asians in your image database? None at all? #IamNotAVirus #COVID19
*******
@AkshayKatariyaa Murder 20k people with zero accountability. Wow. That is covid19 = china originated virus in December 2019.
*******
It is okay to afraid of this covid19,becoz that proof that u are still sane. Just don't be panic pliz.
*******
Tell me how would you fuck me #Norman  #justforyou #coronavirus https://t.co/ks1GIMmni5
*******
Canada, China and the U.S., knew  about this #coronavirus by the end of Dec. All of the early Dec. reports confirmed this. Follow the limited bread crumbs left on the internet. The real shit is being scrubbed clean as we speak. This is a bioengineered virus.
*******
Insane. What about people who may not even like Chinese food? Are they still racist? Or someone who doesn't like Mexican food-still racist? This woman is full goose bozo nuts:
*******
A clip to remember the next time you hear someone lobbying for more courses in humanities in general, and in ethics in particular, for business majors 👇
*******
Dow Tumbles More Than 1000 Points On Fears Of Coronavirus Pandemic #wuhanvirus #coronavirus https://t.co/Mi2rT4X5Dg
*******
@zhaida8 @rickmngmnt @vaibhavsharma84 @cedricarcos @zlj517 @iledefrance @ARS_IDF @Prefet75_IDF @vpecresse @AmbassadeChine @ChooseIDF @lgrotto Look who is talking the Chinese Virus who is raping, killing, eating etc. animals and as well as humans 😆😆
*******
@el_mago_jinete @tyrone_brother Stop eating vermin and exotic animals, you damned slant eyed COVID-19 spreader! Mind YOUR damned business, Ladyboy Ling Ling! 🐀🥡🥢
*******
Nightmare type shit 🙏🏽🙏🏽🙏🏽
*******
@thehill Ain't it awful? It's called the Chinese Virus. Damned Americans just won't take direction from Beijing anymore. Must be all that damned patriotism. Can't seem to get anyone new to commit treason anymore? Have to rely upon the ones you bought years ago? Must really suck to be you.
*******
4,000 in US HOLD CHINA ACCOUNTABLE. If #China fired #Nukes at #USA killing"100K to 240K US" we would have #WW3. So they sent us #coronavirus killing "100K to 240K US".  Sounds like World War Three to me. #CCPVirus #CCP #HoldChinaAccountable
*******
@WBYeats1865 God damn chink. Time to eat some more bat you fucking subhuman
*******
@CNET Fuck chinese editors!  https://t.co/1Z3jf2Tf1d  #ChineseVirus  #COVID19  #coronavirus
*******
Best tweet of the year
*******
@JimHawk67327371 We are. I’m writing a medical article and naming it the Chinese 🦠 Virus. It’s not right that we sh… https://t.co/w6LpCbjViQ
*******
Uncle Joe has a frog in his throat. That or #coronavirus. #DemDebate
*******
@HvBLYabCWxDQEo1 @KingJames Chinese dogs love to suck my dick. If you're coronavirus free then maybe I'll let you swallow.
*******
Fuck the Chinese. Fuck the Europeans too. The Spanish, the Dutch, all them.
*******
Give small business owners a break , anything coming from China is delayed due to coronavirus.. unless you want that shit, relax.
*******
Do you mean Shit Hole China? #ChinaVirus
*******
@Susy71684013 @lynnsprott1 @kdo88 @eugenegu @AllResistNews Chinese govnt waited WEEKS after their first case to admit to the world that this virus was spreading human to human and was an actual threat. China, the CCP and the WHO lied and as a DIRECT result other countries did not consider COVID a threat. China lied, people died.
*******
Dude fuck the Chinese man fuck em and if you think what I’m saying is wrong or rude you’re the problem
*******
NOT #COVIDー19!!  IT SHOULD BE CALLED THE #WuhanVirus !!!!!  Also, Do Not let "WHO" get rid of their responsibility!!  #WuhanCoronavirus  #Wuhan #coronavirus  #FuckCCP #fuckChina #FuckWHO #BoycottChina  #CCP_is_terrorist  #China_is_terrorist  #HongKongisnotChina #TaiwanisnotChina
*******
@HuXijin_GT Here America enjoy your bioweapon we created and sloppily released because our country is an authoritarian hellhole. Stay Strong America! #PROPAGANDA #FuckChina #decouplechina #democracyforchina #chinauprising
*******
@jtao98 Mother Fucking #ChineseVirus
*******
n ppl tried to come at me saying “stop calling it da chinese virus” when they created da shit even after governments stopped funding those dangerous ass trials. look stupid n defend da chinese if u want, they wanted dis to happen.
*******
@Frontalfire I m telling you this is the plan pull out army from border and let chink n pak occupy heights.. This the plan
*******
@LHGHKG @RyanAFournier @Aloha88617098 true "shit" #BoicoteAChina #chinazi  #StandWithHongKong #ChineseWuhanVirus #ChinaLiedAndPeopleDied #ChinaLiedPeopleDied #ChineseVirusCorona #chinaVirusMadeInChina #ChinaMustPay #ChinaWuhanVirus
*******
We do not need China or their communist influence. Stop supporting a dictator and people that are dog eaters! Disgusting!  #AmericansFirst #NoChinaInfuenceOnAmerica #MAGA #coronavirus #StopSellingUsOutToChina #TrumpTrain #TrumpUSA
*******
@atrupar It was a man in my city. Not a woman. He arrived in US from China on Jan 15.
*******
@zlj517 Hello World, Chink man is here. We, Chinese Chinks and CCP comrades, would like to apologize to the world. Our founding father Mao Zedong taught that we CCP members had to lie. Thus, we have to engage in falsehood and deception. Forgive us, lest we forge another virus. https://t.co/GFXhZwez0J
*******
@jling_lee @Exdeeee1 @HuXijin_GT Hello World, Chink man is here. We, Chinese Chinks and CCP comrades, would like to apologize to the world. Our founding father Mao Zedong taught that we CCP members had to lie. Thus, we have to engage in falsehood and deception. Forgive us, lest we forge another virus. https://t.co/PTZVX4zoo9
*******
@m_ebrard Fuck china. #ChinaVirus
*******
@AmbassadorRice @mitchellreports The POTUS does not have an issue with black women. Enough of the race-baiting crap. The real racist is you Susan. And it is not racist-baiting to call it the Wuhan virus. Where did it originate Susan? Why are you pushing China's propaganda? China is our enemy. #RacistRice
*******
@ausgov How about you reconsider our trade arrangements with China and start bringing back to Australia. They can't (but, will) keep getting away with shit like this. #BoycottChina #australiafirst #ChinaLiedPeopleDied
*******
People who survive the chink-virus have an obligation to procreate and pass along their genes. The body goes through a genetic mutation after beating off a virus and it could be beneficial for future generations.
*******
CHINK STINK
*******
THIS! 🔽🔽🔽🔽🔽🔽🔽🔽🔽🔽  One more time: take a deep breath, be sensible, and calm the fuck down.  Don’t let fear overcome your ability to be practical.  #CoronaVirusUpdates #COVID19
*******
@linuxpirategeek @dinamita_uno @wester_sou @SkyNewsAust @Vault82 Australia exports food to the origin off the #Chinavirus China gives us shit cheap socks and shit cheap tvs. So we can keep the food and China can have their sock and keep eating bats.
*******
States have rights, bitch. #ChineseVirus
*******
This is really fucked up. REAL FUCKED UP. #WuhanVirus #COVID19 #ChinaLiedPeopleDied
*******
fucking called that shit from a mile away. I felt u Xi, curfew laws, quarantine, all that on Hong Kong fOr ThE gOoD oF tHe PeOpLe™️ Fuckin commies, burnin’ our women, engineerin’ our churches, rapin’ our viruses.
*******
@BangizweNkosi @alfred_cabonena #Commies the same the world over, consider the asshole #ccp, these dicks would rather kill the entire #World than admit they made a mistake. #Wuhan (more likely on purpose accident) If #coronavirus comes to #SA, patient0 will be #anc connected, cause #cadres steal everything, ne. https://t.co/obaA63fM4X
*******
@isfinalcountdo1 @_taiwano1 #CHINAVIRUS CHINA IS ASS-HOE https://t.co/45g5KsSbf6
*******
Fuck China. Time to become a hermit.
*******
@marklevinshow Jiang, another chink in the fake news media armory waiting to disappear without trace. Where do they find these hideous people? It's like the media are on a mission to self destruct. Is that it?
*******
@cravecreative @Tiamatst81 Horrible stuff. Good for you for showing it. BardsofWar on Youtube has talked about Wuhan being hotbed of Nationalists and Coronavirus may be cover for suppression (and of course the maneStreemMedia somehow does not cover Hong Kong). The gore and filth of communism.
*******

In [10]:
def c_text(comment): 
    comment = comment.lower() # Normalize to lowercase 

    if u'ô' in comment:
        print (comment)
        print("--------------------------------------------")
    return comment

In [4]:
# clean and normalize comments
df['Text'] = df['Text'].map(lambda word:c_text(word))

In [4]:
for x in range(100):
    print(df['Text'][x])
    print ('*******')

I want some chinamen hella bad I wish this coronavirus shit would die down a little 😂😩 damn
*******
@WhiteHouse House Dems want to pass a bill preventing  @realDonaldTrump  from enacting any travel ban at all because of the CoronaVirus. They called the China travel ban "xenophobic" and "racist".  Are they now going to call the EUROPE travel ban "racist"??  Dems have lost their minds!
*******
n ppl tried to come at me saying “stop calling it da chinese virus” when they created da shit even after governments stopped funding those dangerous ass trials. look stupid n defend da chinese if u want, they wanted dis to happen.
*******
@AliciaRedd2 @itsJeffTiedrich @realDonaldTrump I FUCK YOU baby, beautiful Only trump have guts to say CHINESE Virus and to take action against china. https://t.co/VTiOBn27zU
*******
@CoviDcreations @clif_high #coronavirus Report has been published first time and results are extremely serious.   Coronavirus has become the biggest challenge of 2020 in front of Scientists and health experts.  Like, RT: https://t.co/lKia09KKE9 #CoronavirusOutbreak #wuhan #chinavirus #coronaviruschina
*******
#BREAKING: Iraq suspends all flights to Iran due to coronavirus outbreak in country which killed 9 people. https://t.co/ewsOJZLjCX
*******
What Travelers Should Know About Coronavirus https://t.co/3GbPplSqar
*******
Asian Americans join #WashTheHate campaign to raise awareness of discrimination amid coronavirus fears #covid19 https://t.co/mCfhwJWlGx
*******
if we change the human DNA #ThursdayMotivation #DNA #TheDestinyOfLife #SocialJusticeDay #human #DelhiRiots2020 #coronavirus #China #IndiaAgainstCAA   if we change the human DNA .. click hear to this link to know everything    https://t.co/4kIjKKbsd7 https://t.co/2NmYipKTW9
*******
Ayeeee!  Get ready! #LayNewCharitySong  @layzhang @lay_studio
*******
Diagnostics, vaccines, therapeutics. The trinity of weapons against #Covid_19. ⏳⏳⏳ They take time! Leadership, trus… https://t.co/rItMGinSJ7
*******
"Apparently the coronavirus enters a human body through some connection with something called the ACE2 receptor. East Asians and men have more than say white Europeans and women. Being a white woman seems to be the way to have much lesser risk." https://t.co/zSDvzNs1ZX
*******
@GotRailedtoDeth CNN, MSNBC, and every other one of your favorite news channels called it the “wuhan virus” or the “Chinese virus” for almost 6 weeks. Is that racist, too? You’re a special kind of stupid.
*******
Social Media ~Influencers~ need to shut the FUCK up. Nobody cares about the nonsense you have to say buddy, get off the internet! #ChineseVirus #CaroleKilledHerHusband
*******
@PoRiverJamBand @soniagupta504 Globalism unleashing the covid19 virus will kill a thousand times what all hate crimes have. Stop globalism destroying our borders. Never forget the 11,600 Italians who died because globalists brought in 325,000 Chinese workers to keep Gucci purses cheap.
*******
@RealTimBlack @krystalball @esaagar Do you guys heard about COVID-19 at all????
*******
#Covid19 I had purchased some N95 masks 2 months ago. Not many but a box of 15 - never opened it, so I sent them back so that they can be used in the regular supply chain.
*******
@OzonePharma,  #Healthcare delivery needs many people. Doctors are just a part of it. Let's recognize the efforts &amp; dedication of all #healthworkers &amp; not just Doctors.  Such videos say that you are concerned Just for sales by buttering them. #DoctorsSpeakUp #COVID19 #Coronavirus https://t.co/kwMYEeJyJ4
*******
Novel coronavirus many times deadlier then the flu - ABC News https://t.co/e8fimbki4r via @GoogleNews How do you keep pedaling this lie and sleep at night? China has a pop. of 1.4 Billion. Coronavirus started in 11/19 killed 3200, Flu has killed 20,000 in America since Jan-2020.
*******
@BarackObama Fuck you . It’s a Chinese virus moron.  It’s not the result of climate it’s the result of countries that eat weird shit like bats.
*******
@dancezaizai @SteveTheDuckBoi @NineAttributes @RealSaavedra Keep eating bats, and rats, and dogs, and cats and tell us what a civilized country you come from. China owns this pandemic and the entire works knows it! #STFU #KungFlu #FU 🖕🏻 https://t.co/6YEhQRSTkw
*******
@GMA @tzima8 This is not acceptable, Asian Americans have nothing to do with the pandemic. I’m sorry that happened to you Tzi. #WashTheHate
*******
Where was your congressperson when the #WuhanVirus made it to America? #Impeachment and nothing else except to call trump (and us) racists for initiating the chinese travel ban! Keep in mind, today, every country has a travel ban!- is Trudo a racist? #coronavirus #COVID19
*******
Sad truths. Despicable what people are doing to our brothers and sisters in the Asian community. #WashTheHate https://t.co/nb7iS8534M
*******
@gidifeedtv @Gidi_Traffic What's your business with Abba Kyari? Is he the one with the cure and vaccine of #ChineseVirus Just shut the fuck up if you don't have anything positive to say
*******
Communist China doing Communist things. That country is fuckin ass.
*******
Glenn pulled out all the stops for this one. #BigGovVirus https://t.co/KHC7mx6ziA
*******
The Coronavirus, in the United states, reminds me of the movie, Outbreak... This is some scary ass shit. Idk bit something tells me, China has launched a germ warfare against the world...
*******
“After experimenting on animals, if they aren’t dead, they will take the rats and bats and snakes to a local meat market, and sell them for extra money. This could be how the virus got into humans.” - A doctor, on TV, just said this. What the fuck? #coronavirus #ChinaVirus
*******
@wil_silent @ChrisPen2530 @SkyNewsBreak Science bitch! "In 2014, a new theory about the origins of the virus suggested that it first emerged in China, National Geographic reported. Previously undiscovered records linked the flu to the transportation of Chinese laborers" https://t.co/qbLAunmTxw
*******
@TishaCM Why Iran and China has so much victims and casualties from the Covid-19 among countries around the world??..The two countries has no or less human physical contacts among them..Is this a coincidence?
*******
#WashTheHate seeks to bring the Asian community together and create a unified voice that cuts through the noise. https://t.co/pdiMoiO36L
*******
@DrDenaGrayson You dumb ugly ass @realDonaldTrump closed flights from China to stop spread of #ChineseVirus. Then you called him racist.
*******
I have a picture of the fence and trailers but I’m scared they’re going to come knocking at my door in hazmat suits and demand my IPhone.
*******
You know who else is the latest update to the novel coronavirus outbreak? https://t.co/kEw7cHmncQ
*******
@DrTedros @WHO @KingSalman You a bitch. #ChineseBitch #BruceAylward cant even read the word #Taiwan , the best country in fighting #ChineseVirus
*******
@nntaleb, CNN rightly highlights despicable racist attacks on Asians, but then falls back on the “flu kills more people” fallacy :-( https://t.co/JuVJvQqwzG
*******
that British couple on the coronavirus cruise ship who thought because they vote Tory that the government should get Richard Branson to come and rescue them though 👌 when will you people realise that the Tories don't give a fuck about you? the rich are not on your side.
*******
@TrishaPhillipss I’m defo having a vodka &amp; tonic or two later today *chink*
*******
It's a total fucking disgrace that this live animal market that caused this coronavirus is open again selling the SAME animals in the same conditions WHATTHEACCUALFUCK!!! THE WORLD HASN'T LEARNT A LESSON PEOPLES LOVED ONES ARE DYING ALONE! #coronavirus #ChinaVirus
*******
@afneil Ooh that is racist. Reporting facts is racist now. Just like saying the #ChineseVirus originated in #China
*******
For the whole of April, even @YouTube puts video quality restrictions, as if we were already not having enough of those. This Chinese shit is wrecking my nerves now.  #ChinaLiedPeopleDied  #ChinaLiedHDExperienceDied
*******
I wonder if Kayla Williams was given the same level of care as Boris Johnson and deemed a priority as she could not breathe would she still be here with her husband a children. She could not breathe. https://t.co/uFIz1eWoKI
*******
Stop discriminating Asian!Someday you people will get sick too.... #IamNotAVirus
*******
@WHO #ChinaCoronaVirus #ChinaVirus #WuhanCoronaVirus #KungFlu #KungFluFighting #VirusChina #CommunismKills #chicomvirus #ChiCom Bite me bitches!
*******
States have rights, bitch. #ChineseVirus
*******
All #Duterte needed to do was read the script and he still couldn't help himself from sucking Chinese dick! SICK OLD MAN! #CoronavirusPandemic #COVID19 #coronavirus
*******
Coronavirus: How biologists resolved the virus so spectacularly quickly. https://t.co/bLZzdeo20C
*******
“Because half a dozen grasshoppers under a fern make the field ring with their importunate chink, whilst thousands of great cattle... chew the cud and are silent, pray do not imagine that those who make the noise are the only inhabitants of the field.”
*******
If I could take a time machine back six months I wouldn't have stopped most things, including the Wuhan Lab-rat Bat-fuck bio-weapon virus or any personal hurts, but I'd damn well put a stop to that fucking Bob Dylan song with all the ardor left in my now ever-shrinking testicles.
*******
@vipin_cpp @marauder1008 @NPR Later, those media will reactivate the mode of blaming China: our government can't do well in fighting against coronavirus because China didn't share real numbers 😂😂😂😂 Typical Western media😂
*******
Every member of the Executive, Federal, State &amp; Local Governments who failed to heed the  @CDCgov @WHO warnings about #COVID19 #COVID19Pandemic MUST REFUSE ANY &amp; ALL MEDICAL TREATMENT + SIGN A DNR https://t.co/KtbRgqthLX
*******
@tom_cruise31 @hussain_imtiyaz What u want. I am not going to feed in Chinese propaganda. They eat shit and spread virus. This is not the 1st time. Who the hell is going to pay for the loss of lives, economic damage and debt burden in so many countries. CPC is an evil regime &amp; must rightfully be maligned.
*******
@WilsonLeungWS 😴 Chinese products are well known for their poor and cheap quality but all of a suddent this chineese virus proved the world wrong. Fucking chinese🖕🏽 you made the world hell. Just stop eating fucking animals
*******
@ChangshaCity fucking #chinesevirus
*******
Thread about the scapegoating of the Jews over the spread of the Black Death. Parallels with the scapegoating of Chinese people over  Covid19 are striking. People have always been racist pricks
*******
@redsteeze The idiom "chink in one's armor" refers to an area of vulnerability.
*******
China leaked that shit from a lab 100%
*******
@SenKamalaHarris @GOPLeader Hey Kevin - Calling it the "Chinese Coronavirus is racist - but then, you're a hate-mongering bigot so you actually need people to tell you that.
*******
Dear #CoronaVirus please come to India   We feel proud to killed by u rather than killed by Mentally Sick Rioters!   #DelhiRiots2020 #Delhigenocide #CoronaVirusUpdates #CoronavirusOutbreak #coronavirusus #ChinaVirus   @BhavikaKapoor5 @anuragkashyap72 @anuragkashyap72 @ReallySwara
*******
#JeNeSuisPasUnVirus #IAmNotAVirus #我不是病毒  Believe in science,not rumors，GO China!   #我不是病毒 https://t.co/uoUuXdDxEk
*******
One of the many illustrations of how much Chinese lie adding to the many illustrations of why they are not to be trusted yet western governments are following them blindly!  #coronavirus   Luckin, China’s Starbucks Rival, Plunges 81% on Accounting Probe   https://t.co/tEGiWQExw6
*******
#COVID19 fears should not be exploited to attack &amp; exclude minorities – @fernanddev says scapegoating minorities is leading to an alarming rise in verbal &amp; physical abuses against Chinese &amp; other #minorities.  Learn more: https://t.co/LXIaUYZcsg  #IAmNotAVirus #FightRacism https://t.co/kUNG9ectJv
*******
So it's basically a pandemic in Italy now. Not that you'd know from the WHO.   #CoronaVirus #WuFlu #CoVid19
*******
I’d like to share what it’s like on board the Diamond Princess cruise. Please use this page to exchange info. #DiamondPrincess #coronavirus https://t.co/wRLdy63suj
*******
If China can kill us, they can kill you too @AngusCh89615720 @Heefg14 @Jothehkgirl @jonathanseual86 @SammY91318198 @marielSiviglia @op12381932972 @Makhk6 @AWMF5 @HMW79256809 @Senthil557 @wasteslave @valwonghk @SallyGunner0331 @bhikshu2007 @Mark48994372
*******
This is such a dangerous thing to say and I’m disgusted how vile you are for posting this shit, you’re disgusting #ChinaLiedPeopleDied
*******
It is a Chinese Virus  #ChineseVirus
*******
Yt people : create an American parasite I don’t like subtitles! Yt people : I want white people in kpop! Yt people : Asians are spreading the coronavirus and I’m unvaccinated! Yt people: why are so many things about poc now what about us!  The literal fucking stats: https://t.co/Y0PmyC4lRa
*******
@seanhannity Nothing is more disgusting in America than a virus being spread by fake news . 152 countries around the world have citizens dying of a Chinese Pandemic and all the American mainstream media can do is try to blame it all on the US President.
*******
@Haha62181120 @HuXijin_GT FUCK YOU CHINES VIRUS  Name : ChinesVIRUS Birth Place. : WUHAN China Date of Birth : 1st nov 2019 AGE : 5 months Total Crime : 30, 000 Human death Award : CHINES VIRUS noble prize Objective : Destroy Human   FUCK YOU CHINES VIRUS   You eat potty all world sending you CHINESVIRUS
*******
Would you believe anything coming out of China? IMHO anything they say is full of shit!  Communism at its best. Dar… https://t.co/Gb0dUWZhCw
*******
Ignore Trump! Fuck Chinese communists! Used to pile on people for calling it "Chinese Virus". It is fucking "Chinese Virus"! Chinese knew about this contagious virus early on, tried to muzzle those who red flagged it; &amp; made them die. Families of all dead must sue Chinese regime.
*******
@PDChinaBusiness @PDChina #ChineseVirus the dirty people .. fuck the chines minde
*******
@MelissaReddy_ We need to win this game ... considering the fact that corona virus is breathing down our neck
*******
@realDonaldTrump Donald hear this u put a ban on huawei . Their ceo who's from Chinese army fucking took a revenge on you #XiJingping virus. Chinese started world war 3 . What's up with USA
*******
Millions of people could be infected with the #Coronavirus if it turns into a global pandemic. What's fake? What's real? Tune in to @glennbeck’s live special now. #BigGovVirus https://t.co/gT2lcr56an
*******
@dcexaminer @BecketAdams Wuhan, China is a place. Not a race. Discussing the origin of a virus by it's ... origin... is hardly racist. Try again.
*******
Fuck me ive been ordering more chinese in the last week than I have in forever, may as well leave the front door wide open 😂
*******
a virus cannot take on an ethnicity or race dumbass. also, it wouldn’t even be the “chinese virus” because it’s WOR… https://t.co/roQqCbtnId
*******
@zlj517 @mfa_russia ...as the Asian virus. Novel coronavirus began in Wuhan, China. It is quite acceptable to call… https://t.co/ijH2mGslwI
*******
@confusatron WORD Chris !  we just had that press conference televised in the UK ,  smh he is a  embarrassment! " K… https://t.co/aFLTonKMeD
*******
@ArvindKejriwal Why are you praying for their death? Was it necessary to announce these shits at this time? Can't you pray for their good health? Can't you purchase give them good #ChineseVirus prevention kits so that they can work without any fear? @ezdeepak @dsilswal007 @undefinengineer
*******
Following up w/ #racism &amp; #Sinophobia in the UK, here's footage out of Southampton where a group of white kids appear to be attacking Asian-British students for wearing masks going back to their dorm. Disgusting behavior. Pls RT   #RacismIsAVirus #coronavirus  cc: @GoingMedieval https://t.co/zl0pPlJj0E
*******
Asian Americans reported over 650 racists acts last week on website launched by @A3PCON &amp; @CAAsanfrancisco https://t.co/8H4aQqbgRI  Join a townhall on Anti-Asian Racism tomorrow, 3/28 from 6-8pm EST. RSVP here: https://t.co/YIrPfOBxBB   #RacismIsAVirus #coronavirus #COVID19
*******
What. The. Fuck. Is. This. Boomer. Saying. ''Durrr, the DemocRATS released a virus in WUHAN to try and get back a DRUMPF''
*******
SEOUL,Yonhap news says South Korea has reported its first death from a new #coronavirus. South Korean city of Daegu urged its 2.5 million people on Thursday to refrain from going outside as cases of a new virus, linked to a church congregation, spiked. https://t.co/s2PkWvaSbz
*******
@triciaonkiss @tedcruz Oh are you a pyshic can you accurately predict how the virus will kill/ spread or mutate? If not then shut the fuck. #FunFact more people died under Obama from Sars and Ebola then the Chinese Communist Parties Virus
*******
.@DavidHenryHwang is washing his hands to end anti-Asian bigotry with #WashtheHate. https://t.co/X9GlpgrdeL
*******
China let this loose on the world they should pay dearly. Bring our damn supply home back to America and Mexico. We shouldn't be trading with communist China. They are not our friends and never will be. Buy America, look at all the labels. Say no to China.
*******
Hope &amp; Good News 101-year-old Italian man Mr “P” fully recovers from #COVID19 in Italy. Not only did he survive the Chinese Virus disease, the man, born in 1919, fought World War2, also survived the Spanish flu pandemic, which killed approx 50 million people around the world. https://t.co/W4jvAj0IDf
*******
@Birmo @SenatorWong #WarOnChina Everything Points to Biowarfare Being Used Against China by the Western Powers Which Seek to Contain Her Growing Power and Influence in the World https://t.co/DUHWIO4xbw WUHAN CORONAVIRUS PANDEMIC BIOENGINEERED: Who’s behind it, why now and why China?
*******
First Aid Only FAE-4007 SmartCompliance Refill Hand Sanitizer Packets, 10 Count https://t.co/HfOpDmHzfQ ad #coronavirus #coronaoutbreak #CoronavirusOutbreak #coronaviruswuhan #COVID2019 #wuhanvirus #CoronavirusUSA #pandemic #COVIDー19 #nCoV2019 #COVID19US
*******
#china #coronavirus #livestream Let's Talk China - Upcoming Live  Stream Event Trailer https://t.co/YqsgXqQouR via @YouTube
*******
I stand in solidarity with the Chinese people and China.    #IAmNotAVirus  #JeNeSuisPasUnVirus  #coronavirus
*******
"In the West, China is seen as far and removed, and the Sinophobia there tends to be borne out of unfamiliarity. But in Asia and South East Asia it's borne out of too much familiarity.” Analysis written by @tessa_wong 👇
*******
Tonight is my last night of my long vacation in China. Tomorrow night I have to go to bed knowing I have to teach 50+ students Public Speaking online the following morning. How the fuck do you do that? #noclue #China #coronavirus #onlineteaching #FAIL
*******
@CapehartJ you're celebrating the fact that people are losing their pension and retirement?   You're a sick fuck. #WuhanVirus #coronavirus #weak #401k #tsp
*******
Today I stand with my brothers and sisters of Asian descent to remind us that #RacismIsAVirus
*******
Almost half of my colleagues lost their jobs today :( Fuck you #China. Fuck you to the moon. — #ChineseVirus https://t.co/cz1zggvrnu
*******

In [7]:
print(df['Text'][0])

I want some chinamen hella bad I wish this coronavirus shit would die down a little 😂😩 damn

In [177]:
print(df['Text'][1003])

The Asian delegation made a good draft pick in 2004.  #RacismIsAVirus https://t.co/NtMggc40WB

In [178]:
print(df['Text'][606])

Yaa, we won't call it Chinese.  @firkey_ @pokershash  #ChineseVirusCorona #ChineseVirus  #worldlockdown… https://t.co/r2hO6dyFOc

In [201]:
print(df['Text'][98])

Today I stand with my brothers and sisters of Asian descent to remind us that #RacismIsAVirus

In [172]:
print(df['Text'][20])

@dancezaizai @SteveTheDuckBoi @NineAttributes @RealSaavedra Keep eating bats, and rats, and dogs, and cats and tell us what a civilized country you come from. China owns this pandemic and the entire works knows it! #STFU #KungFlu #FU 🖕🏻 https://t.co/6YEhQRSTkw

In [26]:
# remove the 10 most frequent (but keep the first one!)

dellist = pd.Series(' '.join(df['Text']).split()).value_counts()[1:10]
print("COVID-HATE\n")
print(dellist)

COVID-HATE

to         1054
and         779
a           724
of          716
is          667
in          583
Chinese     394
you         394
for         334
dtype: int64

In [36]:
dellist_ = pd.Series(' '.join(df['Text']).split()).value_counts(ascending=True)[1:10]
print("COVID-HATE\n")
print(dellist_)

COVID-HATE

#Lockdown                  1
https://t.co/a6djq47XkD    1
want?                      1
(1/2)                      1
supremacist                1
@KamVTV                    1
https://t.co/TKfZctggLt    1
MSNBC,                     1
💖                          1
dtype: int64

# 3. Preprocessing

In [3]:
stop_words = set(stopwords.words('english'))
import contractions
from nltk.tokenize import word_tokenize
def clean_text(comment): 
   
    #comment = re.sub(r'[^a-zA-Z]', ' ',comment) 
    #comment = re.sub('[\\r\\t\\n]', ' ', comment)
    #comment = re.sub(' +',' ', comment)
    comment = re.sub("@\S+", " ", comment) # Remove usernames
    comment = re.sub("https*\S+", " ", comment) # Remove URL
    #comment = re.sub("\\<([^/> ]+)", " ", comment) # Remove HTML tags
    comment = comment.replace("#", "") #remode hashtag
    #comment = re.sub(r'[^a-zA-Z]', ' ',comment) 
    #comment = re.sub('[\\r\\t\\n]', ' ', comment)
    #comment = re.sub(' +',' ', comment)
    #comment = contractions.fix(comment)
    #months = {m.lower() for m in month_name[1:]}  # create a set of month names
    #for word in comment.split():
    #if word.lower() in months:
        #comment = comment.replace(word, "") 
   
    #word_tokens = word_tokenize(comment)
    # converts the words in word_tokens to lower case and then checks whether 
    #they are present in stop_words or not
    #filtered_sentence = [w for w in word_tokens if not w.lower() in stop_words]
    #with no lower case conversion
    filtered_sentence = []

    #for w in word_tokens:
     #   if w not in stop_words:
      #      filtered_sentence.append(w)
  
 #   sentence = (" ").join(filtered_sentence)
    
    return comment

In [4]:
# clean and normalize comments
df['Text'] = df['Text'].map(lambda word:clean_text(word))

In [5]:
# remove the 10 most frequent (but keep the first one!)

dellist = pd.Series(' '.join(df['Text']).split()).value_counts(ascending=True)[1:100]
print("COVID-HATE\n")
print(dellist)

COVID-HATE

embodiedsolidarity    1
Warning:              1
loosing               1
Bokhari               1
association           1
                     ..
throat.               1
many,                 1
SHIT..CHINA           1
communicate           1
injured               1
Length: 99, dtype: int64

In [8]:
dellist_ = pd.Series(' '.join(df['Text']).split()).value_counts(ascending=True)[41:100]
print("COVID-HATE\n")
print(dellist_)

COVID-HATE

+18                 1
F***                1
aborted             1
alone:              1
Jews:               1
dislike             1
hairy               1
SaudiArabia         1
Spain.              1
decisions.          1
taked               1
distracts           1
kits?               1
imo                 1
Human-To-Human      1
camps.              1
ships.              1
“common             1
Yep                 1
God's               1
AGENCY              1
goal                1
smuggle             1
Anything?           1
Frank               1
actions.            1
f…                  1
Find                1
snakes.             1
ilk                 1
TwitterKingSid      1
tweakin             1
TaiwanIsHelping     1
Tzi                 1
Lmao                1
$1,200              1
13th:               1
'As                 1
y'all!!!!!!!!!!!    1
angels              1
tanks.              1
profiling           1
Theyre              1
freetime            1
anymore.            1
SEOUL,Yonhap        1
Prez.               1
LEARNT              1
Bias                1
“We’re              1
planted             1
defeat              1
Filthy              1
flies               1
throat.             1
many,               1
SHIT..CHINA         1
communicate         1
injured             1
dtype: int64

In [181]:
print(df['Text'][606])

Yaa, we won't call it Chinese.  @firkey_ @pokershash  ChineseVirusCorona ChineseVirus  worldlockdown… https://t.co/r2hO6dyFOc

In [188]:
print(df['Text'][1])

@whitehouse house dems want to pass a bill preventing  @realdonaldtrump  from enacting any travel ban at all because of the coronavirus. they called the china travel ban "xenophobic" and "racist".  are they now going to call the europe travel ban "racist"??  dems have lost their minds!

In [163]:
stop_words = set(stopwords.words('english'))
print(stop_words)

{'our', 'same', 'below', "hadn't", 't', 'those', 'off', "aren't", 'whom', 'other', 'will', 'wasn', 'up', "she's", 'what', 'it', 'your', 'why', 'couldn', 'theirs', 'more', "weren't", 'hadn', 'ain', 'i', 'should', "that'll", 'once', 'has', "won't", 'does', 'm', "it's", 'further', 'its', 'itself', "shouldn't", 'there', 'over', 'she', 'am', 'against', 'above', 'aren', 'yours', 'themselves', "should've", 'so', 'own', "couldn't", 'did', 'some', 'both', 'is', "you'll", 'not', 'shouldn', 'if', 'were', 'they', 'into', 'about', 'mightn', 'few', 'of', 'now', 'after', "didn't", 'but', "mustn't", 'him', 'than', 'which', 'ma', 'nor', 'doesn', 'no', 'having', 'because', 'my', 'with', 'any', "haven't", 'who', 'to', 'very', 'we', 'at', 'a', 'had', 'doing', 'hers', 'too', 'll', 'are', 'o', 'hasn', 'y', 'can', "you'd", 'you', 'being', 'her', 'on', 're', 'was', 'and', 'been', 'out', 'before', 'himself', 'ours', 'wouldn', 'where', 'here', 'ourselves', 'don', 'd', 'his', 'under', 'down', 'between', 'when', 'again', 'the', "shan't", 'me', "isn't", 'mustn', "doesn't", "you're", 've', 'through', 'during', "you've", 'an', 'in', 'most', "wasn't", 'just', 'their', "needn't", "wouldn't", 'myself', 'them', 'or', 'only', 'didn', 'have', 'for', 'won', 'that', 'shan', 'isn', 'from', "mightn't", 'then', 'needn', 'how', 'all', "hasn't", 'each', 'this', 'yourself', 'these', 'yourselves', 'herself', 'while', 'as', 'he', 'by', 's', "don't", 'be', 'do', 'haven', 'weren', 'such', 'until'}

In [164]:
print(df['Text'][26])

Glenn pulled out all the stops for this one. #BigGovVirus https://t.co/KHC7mx6ziA

In [165]:
example_sent = (df['Text'][1003])
from nltk.tokenize import word_tokenize
word_tokens = word_tokenize(example_sent)
# converts the words in word_tokens to lower case and then checks whether 
#they are present in stop_words or not
filtered_sentence = [w for w in word_tokens if not w.lower() in stop_words]
#with no lower case conversion
filtered_sentence = []
  
for w in word_tokens:
    if w not in stop_words:
        filtered_sentence.append(w)
  
print(word_tokens)
print(filtered_sentence)

['The', 'Asian', 'delegation', 'made', 'a', 'good', 'draft', 'pick', 'in', '2004', '.', '#', 'RacismIsAVirus', 'https', ':', '//t.co/NtMggc40WB']
['The', 'Asian', 'delegation', 'made', 'good', 'draft', 'pick', '2004', '.', '#', 'RacismIsAVirus', 'https', ':', '//t.co/NtMggc40WB']

In [166]:
sentence = (" ").join(filtered_sentence)
print(sentence)

The Asian delegation made good draft pick 2004 . # RacismIsAVirus https : //t.co/NtMggc40WB

In [50]:
from string import punctuation
print(punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [32]:
w_tokenizer = nltk.tokenize.WhitespaceTokenizer()
lemmatizer = nltk.stem.WordNetLemmatizer()

def lemmatization(text):
    """This function converts word to their root words 
       without explicitely cut down as done in stemming.
    
    arguments:
         input_text: "text" of type "String".
         
    return:
        value: Text having root words only, no tense form, no plural forms
        
    Example: 
    Input : text reduced 
    Output :  text reduce
    
   """
    # Converting words to their root forms
    lemma = [lemmatizer.lemmatize(w,'v') for w in w_tokenizer.tokenize(text)]
    return lemma

In [47]:
s =  (lemmatization("beautifulness"))

In [48]:
print(s)

['beautifulness']

In [34]:
sentence = (" ").join(s)
print(sentence)

You people love to step on other people, don't you?

In [59]:
import nltk
from nltk.stem import PorterStemmer
w_tokenizer = nltk.tokenize.WhitespaceTokenizer()
word_stemmer = PorterStemmer()
def stemer(text):
      # Converting words to their root forms
    s = [word_stemmer.stem(w,'v') for w in w_tokenizer.tokenize(text)]
    st = (" ").join(s)
    return st
text1 = 'at this point nigga be certify as water lmfaoooo he prolly the one that start that coronavirus 😂😂'
ss = stemer(text1)
#sentence = (" ").join(ss)
#print(sentence)


print(stemer(text1))

at thi point nigga be certifi as water lmfaoooo he prolli the one that start that coronaviru 😂😂

In [60]:
def stem(comment):
    comment= comment.lower()
    for word in comment.split():
        comment = comment.replace(word, word_stemmer.stem(word))
    return comment

In [61]:
from nltk.stem import WordNetLemmatizer
from nltk import word_tokenize,pos_tag


wordnet = WordNetLemmatizer()
def lemmatize_token1 (text):
    s = []
    text= text.lower()

    for token,tag in pos_tag(word_tokenize(text)):
        pos=tag[0].lower()
        
        if pos not in ['a', 'r', 'v', 's']:
            pos='n'
    
        s.append(wordnet.lemmatize(token,pos))
    
    sentence = (" ").join(s)
    return sentence

In [63]:
import contractions
import unicodedata
from spellchecker import SpellChecker
spelling = SpellChecker()

#spelling check
def check_spell(comment): 
    correct_words = []

    comment = comment.lower() # Normalize to lowercase 

    for w in comment.split():
        if w is None:
            continue                
        if len(w)>15 or len(w)==1:
            correct_words.append(w)
        else:
            correct_words.append(spelling.correction(w).lower())
    cor_comment = ' '.join(correct_words) 
    return cor_comment

In [64]:
# remove accented characters
def remove_accented_chars(text):
    new_text = unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8', 'ignore')
    return new_text

In [68]:
text = '« Ya\'ll take note. There ain\'t never tornadoes where colored folk live we r nt stupid pathtic kids u r u fat shite '

import contractions
import unicodedata
comment = text.lower() # Normalize to lowercase 
comment = remove_accented_chars(comment) # remove accented characters
comment = contractions.fix(comment) # fix contractions
comment = lemmatize_token1(comment)
comment = stem(comment)
print(comment)

ya 'll take note . there be not never tornado where color folk live we r nt stupid pathtic kid you r you fat shite

In [70]:
def print_text(sample, clean):
    print(f"Before: {sample}")
    print(f"After: {clean}")

In [72]:
tokens = comment.split()
clean_tokens = [t for t in tokens if len(t) > 2]
clean_text = " ".join(clean_tokens)
print_text(comment, clean_text)

Before: ya 'll take note . there be not never tornado where color folk live we r nt stupid pathtic kid you r you fat shite
After: 'll take note there not never tornado where color folk live stupid pathtic kid you you fat shite

In [48]:
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
wordnet_map = {"N":wordnet.NOUN, "V":wordnet.VERB, "J":wordnet.ADJ, "R":wordnet.ADV} # Pos tag, used Noun, Verb, Adjective and Adverb
# Function for lemmatization using POS tag
def lemmatize_words(text):
    pos_tagged_text = nltk.pos_tag(text.split())
    return " ".join([lemmatizer.lemmatize(word, wordnet_map.get(pos[0], wordnet.NOUN)) for word, pos in pos_tagged_text])
# Passing the function to 'text_rare' and store in 'text_lemma'
#df["text_lemma"] = df["text_rare"].apply(lemmatize_words)

In [67]:
s =  (lemmatization("aardwolves"))
sentence = (" ").join(s)
print(sentence)

aardwolves

In [72]:
from nltk.stem import WordNetLemmatizer
wnl = WordNetLemmatizer()
print(wnl.lemmatize('dogs'))
#dog
print(wnl.lemmatize('churches'))
#church
print(wnl.lemmatize('aardwolves'))
#aardwolf
print(wnl.lemmatize('abaci'))
#abacus
print(wnl.lemmatize('hardrock'))
#hardrock
print(wnl.lemmatize('doing'))

dog
church
aardwolf
abacus
hardrock
doing

In [66]:
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

text = "Glenn pulled out all the stops for this one. #BigGovVirus https://t.co/KHC7mx6ziA"
wordnet = WordNetLemmatizer()
tokenizer = word_tokenize(text)
s = []

for token in tokenizer:
    s.append(wordnet.lemmatize(token))
sentence = (" ").join(s)
print(sentence)

Glenn pulled out all the stop for this one . # BigGovVirus http : //t.co/KHC7mx6ziA

In [12]:
from nltk.stem import WordNetLemmatizer
from nltk import word_tokenize,pos_tag

text1 = "This is such a dangerous thing to say and I’m disgusted how vile you are for posting this shit, you’re disgusting #ChinaLiedPeopleDied"
wordnet = WordNetLemmatizer()
def lemmatize_token1 (text):
    s = []

    for token,tag in pos_tag(word_tokenize(text)):
        pos=tag[0].lower()
        
        if pos not in ['a', 'r', 'v', 's']:
            pos='n'
    
        s.append(wordnet.lemmatize(token,pos))
    
    sentence = (" ").join(s)
    return sentence
print(lemmatize_token1(text1))

This be such a dangerous thing to say and I ’ m disgust how vile you be for post this shit , you ’ re disgust # ChinaLiedPeopleDied

In [129]:
from nltk.stem import WordNetLemmatizer
from nltk import word_tokenize,pos_tag

wordnet = WordNetLemmatizer()
def lemmatize_token (text):
    lemma = []

    for token,tag in pos_tag(word_tokenize(text)):
        pos = tag[0].lower()        
        if pos not in ['v', 'r', 'a', 's']:
            pos = 'n'    
        lemma.append(wordnet.lemmatize(token,pos))    
    sentence = (" ").join(s)
    return sentence

In [130]:
print(lemmatize_token(text1))

using returned sweetly aardwolf

In [26]:
print("Ensemble de données HatEval")
df.isnull().sum()

Ensemble de données HatEval

Tweet ID    0
Text        0
tox         0
dtype: int64

In [9]:
import datetime
start = '01MAY2017 11:45'
print (start_date.strftime('%d%b%Y %H:%M'))
start_date = datetime.datetime.strptime(start, '%d%b%Y %H:%M').date()
comment = '01MAY2017 11:45 hgwj fwkhw je'
comment = comment.replace('%d%b%Y %H:%M', " ")
print (comment)

01May2017 00:00
01MAY2017 11:45 hgwj fwkhw je

In [14]:
import re
found = ''
text = '2/17/1937 00:00:00:00'

m = re.search('(.*)\s[0\:]*$', text)
if m:
    found = m.group(1);
    print (found)

2/17/1937

In [24]:
from datetime_extractor import DateTimeExtractor
import re

samplestring1 = 'scala> val xorder= new order(1,"2016-02-22 00:00:00.00",100,"COMPLETED") Fri,  Jun ' 
y = DateTimeExtractor(samplestring1)
print(y)
for date in y:
    samplestring1 = samplestring1.replace(date, ' ')
print(samplestring1)

['2016-02-22 00:00:00.00']
scala> val xorder= new order(1," ",100,"COMPLETED") Fri,  Jun

In [17]:
samplestring2 = 'Fri, 10 Jun 2011 11:04:17 +0200 (CEST)'

x = DateTimeExtractor(samplestring2)

['10 Jun 2011 11:04:17']