# Toxic Comments Classification - SVM

#### Author: SAFAA ENNACIRI - ENNS11538307                                 
#### Research Director: M. HAKIM LOUNIS

Dataset: Toxic Comment Classification dataset is a dataset of comments from Wikipedia’s talk page edits.  It is avaialble at Kaggle (https://www.kaggle.com/c/jigsaw-toxic-comment-classification-challenge/data). 


The comments are devided in two categories: toxic and normal.

Algorithme used: SVM

Technique used: GreadSearchCV

# 1. Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import pickle, time

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

from sklearn.pipeline import Pipeline, make_pipeline
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score, precision_recall_fscore_support, accuracy_score
from skmultilearn.problem_transform import BinaryRelevance
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

# 2. Data Preparation

## 2.1 Load and explore data

In [2]:
# Load training data
df = pd.read_csv('../../Data/train_set1.csv')
df.head()

                 id                                       comment_text  tox
0  20ca7bad20d4c3d1  You're an asshole, useless piece of shit. Get ...    1
1  72428510d4205ccf  Nonito Donaire \n\nIt is clearly stated in the...    0
2  f3890d4a31f0d45a  Okay, in the future I shall no longer use the ...    0
3  29ac5b2897f7ef59         fuck off \n\ndon't fuck with me . fuck off    1
4  6f2278059a63256a  "*E-dog, on another page, you wrote: \n\nThank...    1

In [3]:
# Load testing data
test = pd.read_csv('../../Data/test_set1.csv')
test.head()

                 id                                       comment_text  tox
0  b28eeb594e5ac00f  AAAAWWWW, widdle wikinazis banned me.\n\nMaybe...    1
1  2f3c460abcd5479f  very crocker sucks n e g r o c o c k s i n h e...    1
2  dc3ae57fa0c30d8d               He lied on my RFC too.  He's a liar.    1
3  5eb7bb36f870d2b9  "I've removed the following:\n""Morro Bay is a...    0
4  e9c9d9abd37bca1d  Briefcase\n\nToo much importance is given to t...    0

In [4]:
X_train = df['comment_text']
Y_train = df['tox']

#Check shape of data
print(X_train.shape)
print(Y_train.shape)

(25960,)
(25960,)

In [5]:
X_test = test['comment_text']
Y_test = test['tox']

#Check shape of data
print(X_test.shape)
print(Y_test.shape)

(6490,)
(6490,)

# 3. Classifier training

## 3.1 Create pipeline

In [6]:
start_time=time.time()

SVC_pipeline1 = make_pipeline(TfidfVectorizer(),
                SVC(verbose=True))


param_grid = {'svc__kernel': ['linear','sigmoid','rbf', 'poly'], 
              'svc__gamma': ['auto', 'scale']
             } 

            
grid_3 = GridSearchCV(SVC_pipeline1, param_grid, cv=10, scoring='accuracy', error_score='raise')

grid = grid_3 .fit(X_train, Y_train)

end_time=time.time()
              
print("total time",end_time-start_time)

[LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM][LibSVM]total time 22500.529824972153

In [7]:
# Print the model parameters of the best estimator
print(grid.best_estimator_.named_steps['svc'])

SVC(gamma='auto', kernel='linear', verbose=True)

In [8]:
# Print the model parameters of the best model
grid.best_params_

{'svc__gamma': 'auto', 'svc__kernel': 'linear'}

In [9]:
# Print the training score of the best model
print('Test accuracy: %.3f' % grid.best_score_)

Test accuracy: 0.903

In [10]:
# Print the test score of the best model
best_estimator = grid.best_estimator_
print('Test accuracy: %.3f' % best_estimator.score(X_test, Y_test))

Test accuracy: 0.903